export const LOGIN_INITIALIZE = "LOGIN_INITIALIZE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_INITIALIZE = "SIGNUP_INITIALIZE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const FETCH_LOCATIONS_INITIALIZE = "FETCH_LOCATIONS_INITIALIZE";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_FACTORS_INITIALIZE = "FETCH_FACTORS_INITIALIZE";
export const FETCH_FACTORS_SUCCESS = "FETCH_FACTORS_SUCCESS";
export const FETCH_FACTORS_FAIL = "FETCH_FACTORS_FAIL";
